name: Fetch GitHub Repos

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  fetch-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          npm install

      - name: Compile TypeScript (GitHub Repos)
        run: |
          npx tsx scripts/fetchGitHubRepos.ts

      - name: Commit and push updated repos file
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add ./public/github-repos.json
          git commit -m "Update GitHub repositories" || echo "No changes to commit"
          git push origin main
