name: Fetch GitHub Activity

on:
  schedule:
    - cron: "0 11,15,19 * * *"
  workflow_dispatch:

jobs:
  fetch-activity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          npm install

      - name: Compile TypeScript (GitHub Activity)
        run: |
          npx tsc scripts/fetchGitHubActivity.ts

      - name: Run GitHub Activity script
        run: |
          node scripts/fetchGitHubActivity.js

      - name: Commit and push updated activity file
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add ./public/github-activity.json
          git commit -m "Update GitHub activity" || echo "No changes to commit"
          git push
