name: Test GitHub Action

on:
  schedule:
    - cron: "00 1 * * *"
  workflow_dispatch:

jobs:
  run-test-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install

      - name: Compile TypeScript (GitHub Activity)
        run: |
          npx tsc app/scripts/fetchGitHubActivity.ts

      - name: Run GitHub Activity script
        run: |
          node app/scripts/fetchGitHubActivity.js
